<a href="https://colab.research.google.com/github/Eurukaki/23spring_DL_homeworks/blob/main/HW1Q3(a).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
##reference:https://blog.csdn.net/deephub/article/details/107503883

##dataset1

import torch
import plotly.graph_objects as go
import numpy as np

# Batch Size, Input Neurons, Hidden Neurons, Output Neurons
#for learning rate = 1e-3, 40000 iterations, the model can fit the data perfectly.
#N, D_in, H, D_out = 1, 1, 1024, 1
#just 4 neurons' model can not fit the data very well, the minimal loss is about 11 or 24.
N, D_in, H, D_out = 13, 1, 4, 1

# Create random Tensors to hold inputs and outputs

x = torch.FloatTensor([[0],[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12]])
y = torch.FloatTensor([[8],[6],[4],[2],[0],[2],[4],[2],[0],[2],[4],[6],[8]])



# Use the nn package to define our model
# Linear (Input -> Hidden), ReLU (Non-linearity), Linear (Hidden-> Output)
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

# Define the loss function: Mean Squared Error
# The sum of the squares of the differences between prediction and ground truth
loss_fn = torch.nn.MSELoss(reduction='sum')

# The optimizer does a lot of the work of actually calculating gradients and
# applying backpropagation through the network to update weights
# lr = 0.1 or 0.05 is alright
learning_rate = 0.1
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


# Perform 6000 training steps
for t in range(6000):
    # Forward pass: compute predicted y by passing x to the model.
    y_pred = model(x)

    # Compute loss and print it periodically
    loss = loss_fn(y_pred, y)
    if t % 100 == 0:
        print(t, loss.item())

    # Update the network weights using gradient of the loss
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
###################################################
# Draw the original random points as a scatter plot
fig = go.Figure()
fig.add_trace(go.Scatter(x=x.flatten().numpy(), y=y.flatten().numpy(), mode="markers"))

# Generate predictions for evenly spaced x-values between minx and maxx
minx = min(list(x.numpy()))
maxx = max(list(x.numpy()))
c = torch.from_numpy(np.linspace(minx, maxx, num=640)).reshape(-1, 1).float()
d = model(c)

# Draw the predicted functions as a line graph
fig.add_trace(go.Scatter(x=c.flatten().numpy(), y=d.flatten().detach().numpy(), mode="lines"))
fig.show()

# Show corresponding name of every layer
for name in model.state_dict():
  print(name)

# Print weights and bias of certain layers
print(model.state_dict()['0.weight'])
print(model.state_dict()['0.bias'])
print(model.state_dict()['2.weight'])
print(model.state_dict()['2.bias'])


0 211.69175720214844
100 27.430173873901367
200 24.823503494262695
300 24.81497573852539
400 24.83965492248535
500 24.87290382385254
600 24.81123161315918
700 24.814489364624023
800 24.84393882751465
900 24.81330680847168
1000 24.809892654418945
1100 24.816162109375
1200 24.806371688842773
1300 24.820297241210938
1400 24.802967071533203
1500 24.87872314453125
1600 24.812808990478516
1700 24.853515625
1800 24.813066482543945
1900 24.802722930908203
2000 24.799701690673828
2100 24.8140926361084
2200 24.80915069580078
2300 24.811464309692383
2400 24.815628051757812
2500 24.82349967956543
2600 24.839759826660156
2700 24.835386276245117
2800 24.862417221069336
2900 24.808595657348633
3000 24.92144203186035
3100 24.818214416503906
3200 24.834257125854492
3300 24.832571029663086
3400 24.818368911743164
3500 24.811681747436523
3600 24.82567024230957
3700 24.82647705078125
3800 24.8382625579834
3900 24.837678909301758
4000 24.810365676879883
4100 24.81277847290039
4200 24.839752197265625
4300 2

0.weight
0.bias
2.weight
2.bias
tensor([[-0.8179],
        [-1.0889],
        [-0.1542],
        [ 0.9512]])
tensor([ 1.0180,  4.2845, -0.0436, -1.1842])
tensor([[-0.8966,  2.5103,  0.2029,  0.7706]])
tensor([-1.8431])


In [83]:
##reference:https://blog.csdn.net/deephub/article/details/107503883

##dataset2

import torch
import plotly.graph_objects as go
import numpy as np

# Batch Size, Input Neurons, Hidden Neurons, Output Neurons
#just 4 neurons' model can not fit the data very well, the minimal loss is about 11 or 24.
N, D_in, H, D_out = 11, 1, 4, 1

# Create random Tensors to hold inputs and outputs

x = torch.FloatTensor([[0],[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
y = torch.FloatTensor([[0],[1],[2],[3],[2],[1],[1.5],[2],[2.5],[3],[3.5]])



# Use the nn package to define our model
# Linear (Input -> Hidden), ReLU (Non-linearity), Linear (Hidden-> Output)
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

# Define the loss function: Mean Squared Error
# The sum of the squares of the differences between prediction and ground truth
loss_fn = torch.nn.MSELoss(reduction='sum')

# The optimizer does a lot of the work of actually calculating gradients and
# applying backpropagation through the network to update weights
learning_rate = 0.1
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


# Perform 6000 training steps
for t in range(6000):
    # Forward pass: compute predicted y by passing x to the model.
    y_pred = model(x)

    # Compute loss and print it periodically
    loss = loss_fn(y_pred, y)
    if t % 100 == 0:
        print(t, loss.item())

    # Update the network weights using gradient of the loss
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
###################################################
# Draw the original random points as a scatter plot
fig = go.Figure()
fig.add_trace(go.Scatter(x=x.flatten().numpy(), y=y.flatten().numpy(), mode="markers"))

# Generate predictions for evenly spaced x-values between minx and maxx
minx = min(list(x.numpy()))
maxx = max(list(x.numpy()))
c = torch.from_numpy(np.linspace(minx, maxx, num=640)).reshape(-1, 1).float()
d = model(c)

# Draw the predicted functions as a line graph
fig.add_trace(go.Scatter(x=c.flatten().numpy(), y=d.flatten().detach().numpy(), mode="lines"))
fig.show()

# Show corresponding name of every layer
for name in model.state_dict():
  print(name)

# Print weights and bias of certain layers
print(model.state_dict()['0.weight'])
print(model.state_dict()['0.bias'])
print(model.state_dict()['2.weight'])
print(model.state_dict()['2.bias'])


0 264.0760803222656
100 1.989653468132019
200 0.9532971382141113
300 0.232213094830513
400 0.025210287421941757
500 0.0016367936041206121
600 4.016231105197221e-05
700 5.812695462736883e-07
800 4.275747755855264e-09
900 1.9539925233402755e-11
1000 7.44648787076585e-12
1100 3.907985046680551e-12
1200 3.782439534916193e-07
1300 0.00023217909620143473
1400 2.205595706072927e-09
1500 5.922132118030277e-09
1600 1.0433609531901311e-10
1700 1.0942358130705543e-12
1800 1.1377778719179332e-09
1900 0.02222115732729435
2000 0.0007015385781414807
2100 0.005542766768485308
2200 0.0020148777402937412
2300 4.547107579355725e-09
2400 1.6473933328597923e-11
2500 2.3163693185779266e-12
2600 6.549938689204282e-07
2700 0.029717667028307915
2800 7.981633984854852e-07
2900 1.3520235597752617e-06
3000 0.005516626872122288
3100 7.953169642860303e-07
3200 0.0001572420442244038
3300 0.000635092961601913
3400 0.0012497443240135908
3500 1.7729861383486423e-06
3600 1.9669865650939755e-05
3700 0.0024339763913303614

0.weight
0.bias
2.weight
2.bias
tensor([[ 0.7311],
        [-0.9744],
        [-0.8779],
        [-0.9986]])
tensor([-3.6558, -0.5731,  4.3882,  2.9951])
tensor([[ 0.6838,  0.4101,  1.1407, -2.0039]])
tensor([1.0003])
