<a href="https://colab.research.google.com/github/Eurukaki/23spring_DL_homeworks/blob/main/HW1Q3(a).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
##reference:https://blog.csdn.net/deephub/article/details/107503883

import torch
import plotly.graph_objects as go
import numpy as np

# Batch Size, Input Neurons, Hidden Neurons, Output Neurons
#for learning rate = 1e-3, 40000 iterations, the model can fit the data perfectly.
#N, D_in, H, D_out = 1, 1, 1024, 1
#just 4 neurons' model can not fit the data very well, the minimal loss is about 11
N, D_in, H, D_out = 13, 1, 4, 1

# Create random Tensors to hold inputs and outputs

x = torch.FloatTensor([[0],[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12]])
y = torch.FloatTensor([[8],[6],[4],[2],[0],[2],[4],[2],[0],[2],[4],[6],[8]])



# Use the nn package to define our model
# Linear (Input -> Hidden), ReLU (Non-linearity), Linear (Hidden-> Output)
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

# Define the loss function: Mean Squared Error
# The sum of the squares of the differences between prediction and ground truth
loss_fn = torch.nn.MSELoss(reduction='sum')

# The optimizer does a lot of the work of actually calculating gradients and
# applying backpropagation through the network to update weights
learning_rate = 0.1
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


# Perform 5000 training steps
for t in range(6000):
    # Forward pass: compute predicted y by passing x to the model.
    y_pred = model(x)

    # Compute loss and print it periodically
    loss = loss_fn(y_pred, y)
    if t % 100 == 0:
        print(t, loss.item())

    # Update the network weights using gradient of the loss
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
###################################################
# Draw the original random points as a scatter plot
fig = go.Figure()
fig.add_trace(go.Scatter(x=x.flatten().numpy(), y=y.flatten().numpy(), mode="markers"))

# Generate predictions for evenly spaced x-values between minx and maxx
minx = min(list(x.numpy()))
maxx = max(list(x.numpy()))
c = torch.from_numpy(np.linspace(minx, maxx, num=640)).reshape(-1, 1).float()
d = model(c)

# Draw the predicted functions as a line graph
fig.add_trace(go.Scatter(x=c.flatten().numpy(), y=d.flatten().detach().numpy(), mode="lines"))
fig.show()

# Show corrosponding name of every layer
for name in model.state_dict():
  print(name)

# Print weights and bias of certain layers
print(model.state_dict()['0.weight'])
print(model.state_dict()['0.bias'])
print(model.state_dict()['2.weight'])
print(model.state_dict()['2.bias'])


0 232.82376098632812
100 28.554309844970703
200 11.241827964782715
300 11.199999809265137
400 11.200000762939453
500 11.19999885559082
600 11.19999885559082
700 11.19999885559082
800 11.212255477905273
900 11.19999885559082
1000 11.19999885559082
1100 11.31435489654541
1200 11.200000762939453
1300 11.200000762939453
1400 11.247584342956543
1500 11.200102806091309
1600 11.199999809265137
1700 11.19999885559082
1800 11.199999809265137
1900 11.200000762939453
2000 11.46457290649414
2100 11.20000171661377
2200 11.199999809265137
2300 11.233207702636719
2400 11.200008392333984
2500 11.19999885559082
2600 11.199999809265137
2700 11.200094223022461
2800 11.200000762939453
2900 11.200132369995117
3000 11.200067520141602
3100 11.200000762939453
3200 11.200056076049805
3300 11.19999885559082
3400 11.200005531311035
3500 11.200163841247559
3600 11.200000762939453
3700 11.246686935424805
3800 11.200002670288086
3900 11.200000762939453
4000 11.204695701599121
4100 11.19999885559082
4200 11.20011425

0.weight
0.bias
2.weight
2.bias
tensor([[-1.2415],
        [-0.1215],
        [-0.0322],
        [ 1.1207]])
tensor([ 3.9728, -1.2099, -0.4355, -9.8617])
tensor([[ 1.6110, -0.2561,  0.3415,  1.7847]])
tensor([1.6000])
