<a href="https://colab.research.google.com/github/Eurukaki/23spring_DL_homeworks/blob/main/HW1Q3(a).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
##reference:https://blog.csdn.net/deephub/article/details/107503883

import torch
import plotly.graph_objects as go
import numpy as np

# Batch Size, Input Neurons, Hidden Neurons, Output Neurons
#for learning rate = 1e-3, 40000 iterations, the model can fit the data perfectly.
#N, D_in, H, D_out = 1, 1, 1024, 1
#just 4 neurons' model can not fit the data very well, the minimal loss is about 11 or 24.
N, D_in, H, D_out = 13, 1, 4, 1

# Create random Tensors to hold inputs and outputs

x = torch.FloatTensor([[0],[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12]])
y = torch.FloatTensor([[8],[6],[4],[2],[0],[2],[4],[2],[0],[2],[4],[6],[8]])



# Use the nn package to define our model
# Linear (Input -> Hidden), ReLU (Non-linearity), Linear (Hidden-> Output)
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

# Define the loss function: Mean Squared Error
# The sum of the squares of the differences between prediction and ground truth
loss_fn = torch.nn.MSELoss(reduction='sum')

# The optimizer does a lot of the work of actually calculating gradients and
# applying backpropagation through the network to update weights
# lr = 0.1 or 0.05 is alright
learning_rate = 0.1
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


# Perform 6000 training steps
for t in range(6000):
    # Forward pass: compute predicted y by passing x to the model.
    y_pred = model(x)

    # Compute loss and print it periodically
    loss = loss_fn(y_pred, y)
    if t % 100 == 0:
        print(t, loss.item())

    # Update the network weights using gradient of the loss
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
###################################################
# Draw the original random points as a scatter plot
fig = go.Figure()
fig.add_trace(go.Scatter(x=x.flatten().numpy(), y=y.flatten().numpy(), mode="markers"))

# Generate predictions for evenly spaced x-values between minx and maxx
minx = min(list(x.numpy()))
maxx = max(list(x.numpy()))
c = torch.from_numpy(np.linspace(minx, maxx, num=640)).reshape(-1, 1).float()
d = model(c)

# Draw the predicted functions as a line graph
fig.add_trace(go.Scatter(x=c.flatten().numpy(), y=d.flatten().detach().numpy(), mode="lines"))
fig.show()

# Show corresponding name of every layer
for name in model.state_dict():
  print(name)

# Print weights and bias of certain layers
print(model.state_dict()['0.weight'])
print(model.state_dict()['0.bias'])
print(model.state_dict()['2.weight'])
print(model.state_dict()['2.bias'])


0 331.72393798828125
100 26.014610290527344
200 24.858661651611328
300 24.857147216796875
400 24.857141494750977
500 24.857141494750977
600 24.85714340209961
700 24.85714340209961
800 24.857139587402344
900 24.85714340209961
1000 24.85714340209961
1100 24.85714340209961
1200 24.857139587402344
1300 24.857141494750977
1400 24.857141494750977
1500 24.857141494750977
1600 24.857141494750977
1700 24.85714340209961
1800 24.857141494750977
1900 24.85714340209961
2000 24.857145309448242
2100 24.857141494750977
2200 24.85714340209961
2300 12.010709762573242
2400 11.200056076049805
2500 11.200000762939453
2600 11.199999809265137
2700 11.200000762939453
2800 11.200000762939453
2900 11.199999809265137
3000 11.200000762939453
3100 11.200000762939453
3200 11.200000762939453
3300 11.200000762939453
3400 11.200000762939453
3500 11.200000762939453
3600 11.200000762939453
3700 11.200000762939453
3800 11.200000762939453
3900 11.200000762939453
4000 12.256715774536133
4100 11.200127601623535
4200 11.2000

0.weight
0.bias
2.weight
2.bias
tensor([[-0.8821],
        [ 0.8709],
        [-0.0306],
        [-0.2494]])
tensor([ 2.8229, -7.6637, -0.5759, -0.7624])
tensor([[ 2.2672,  2.2966, -0.1872,  0.2837]])
tensor([1.6000])
