<a href="https://colab.research.google.com/github/Eurukaki/23spring_DL_homeworks/blob/main/HW1Q3(a).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import torch
import plotly.graph_objects as go
import numpy as np

# Batch Size, Input Neurons, Hidden Neurons, Output Neurons
N, D_in, H, D_out = 13, 1, 4, 1

# Create random Tensors to hold inputs and outputs
#x = torch.randn(N, D_in)
#y = torch.randn(N, D_out)
#x = torch.tensor([0,1,2,3,4,5,6,7,8,9,10,11,12])
#y = torch.tensor([8,6,4,2,0,2,4,2,0,2,4,6,8])

x = torch.FloatTensor([[0],[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12]])
y = torch.FloatTensor([[8],[6],[4],[2],[0],[2],[4],[2],[0],[2],[4],[6],[8]])



# Use the nn package to define our model
# Linear (Input -> Hidden), ReLU (Non-linearity), Linear (Hidden-> Output)
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

# Define the loss function: Mean Squared Error
# The sum of the squares of the differences between prediction and ground truth
loss_fn = torch.nn.MSELoss(reduction='sum')

# The optimizer does a lot of the work of actually calculating gradients and
# applying backpropagation through the network to update weights
#learning_rate = 1e-4
learning_rate = 0.1
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# Perform 30000 training steps
for t in range(5000):
    # Forward pass: compute predicted y by passing x to the model.
    y_pred = model(x)

    # Compute loss and print it periodically
    loss = loss_fn(y_pred, y)
    if t % 100 == 0:
        print(t, loss.item())

    # Update the network weights using gradient of the loss
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
###################################################
# Draw the original random points as a scatter plot
fig = go.Figure()
fig.add_trace(go.Scatter(x=x.flatten().numpy(), y=y.flatten().numpy(), mode="markers"))

# Generate predictions for evenly spaced x-values between minx and maxx
minx = min(list(x.numpy()))
maxx = max(list(x.numpy()))
c = torch.from_numpy(np.linspace(minx, maxx, num=640)).reshape(-1, 1).float()
d = model(c)

# Draw the predicted functions as a line graph
fig.add_trace(go.Scatter(x=c.flatten().numpy(), y=d.flatten().detach().numpy(), mode="lines"))
fig.show()

for name in model.state_dict():
  print(name)

print(model.state_dict()['0.weight'])
print(model.state_dict()['0.bias'])
print(model.state_dict()['2.weight'])
print(model.state_dict()['2.bias'])


0 221.22482299804688
100 25.317764282226562
200 24.656723022460938
300 24.624164581298828
400 24.625823974609375
500 24.622604370117188
600 24.622222900390625
700 24.62221908569336
800 24.622222900390625
900 24.622222900390625
1000 24.622220993041992
1100 24.622220993041992
1200 24.62221908569336
1300 24.622224807739258
1400 24.622220993041992
1500 24.622222900390625
1600 24.622220993041992
1700 24.622222900390625
1800 24.622220993041992
1900 24.622222900390625
2000 24.622316360473633
2100 24.622224807739258
2200 24.622222900390625
2300 24.622224807739258
2400 24.622228622436523
2500 24.622222900390625
2600 24.622220993041992
2700 24.722293853759766
2800 24.622230529785156
2900 24.622222900390625
3000 24.622222900390625
3100 24.622220993041992
3200 24.622220993041992
3300 24.622358322143555
3400 24.622228622436523
3500 24.622220993041992
3600 24.622316360473633
3700 24.622220993041992
3800 24.622220993041992
3900 24.64777183532715
4000 24.622228622436523
4100 24.622220993041992
4200 24

0.weight
0.bias
2.weight
2.bias
tensor([[ 0.9155],
        [-0.1960],
        [-0.4511],
        [-0.8247]])
tensor([-3.6009, -0.4158,  1.6003,  3.2765])
tensor([[ 0.8008, -0.3940,  0.3896,  2.2121]])
tensor([0.1283])
