<a href="https://colab.research.google.com/github/Eurukaki/23spring_DL_homeworks/blob/main/HW1Q3(a).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
##reference:https://blog.csdn.net/deephub/article/details/107503883

##dataset1

import torch
import plotly.graph_objects as go
import numpy as np

# Batch Size, Input Neurons, Hidden Neurons, Output Neurons
#for learning rate = 1e-3, 40000 iterations, the model can fit the data perfectly.
#N, D_in, H, D_out = 1, 1, 1024, 1
#just 4 neurons' model can not fit the data very well, the minimal loss is about 11 or 24.
N, D_in, H, D_out = 3, 1, 4, 1

# Create random Tensors to hold inputs and outputs

x = torch.FloatTensor([[0],[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12]])
y = torch.FloatTensor([[8],[6],[4],[2],[0],[2],[4],[2],[0],[2],[4],[6],[8]])



# Use the nn package to define our model
# Linear (Input -> Hidden), ReLU (Non-linearity), Linear (Hidden-> Output)
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

# Define the loss function: Mean Squared Error
# The sum of the squares of the differences between prediction and ground truth
loss_fn = torch.nn.MSELoss(reduction='sum')

# The optimizer does a lot of the work of actually calculating gradients and
# applying backpropagation through the network to update weights
# lr = 0.1 or 0.05 is alright
learning_rate = 0.01
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


# Perform 6000 training steps
for t in range(10000):
    # Forward pass: compute predicted y by passing x to the model.
    y_pred = model(x)

    # Compute loss and print it periodically
    loss = loss_fn(y_pred, y)
    if t % 100 == 0:
        print(t, loss.item())

    # Update the network weights using gradient of the loss
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
###################################################
# Draw the original random points as a scatter plot
fig = go.Figure()
fig.add_trace(go.Scatter(x=x.flatten().numpy(), y=y.flatten().numpy(), mode="markers"))

# Generate predictions for evenly spaced x-values between minx and maxx
minx = min(list(x.numpy()))
maxx = max(list(x.numpy()))
c = torch.from_numpy(np.linspace(minx, maxx, num=640)).reshape(-1, 1).float()
d = model(c)

# Draw the predicted functions as a line graph
fig.add_trace(go.Scatter(x=c.flatten().numpy(), y=d.flatten().detach().numpy(), mode="lines"))
fig.show()

# Show corresponding name of every layer
for name in model.state_dict():
  print(name)

# Print weights and bias of certain layers
print(model.state_dict()['0.weight'])
print(model.state_dict()['0.bias'])
print(model.state_dict()['2.weight'])
print(model.state_dict()['2.bias'])


0 179.58895874023438
100 76.4637451171875
200 41.225154876708984
300 35.98298645019531
400 30.49875831604004
500 25.48540687561035
600 24.64731216430664
700 24.62245750427246
800 24.62221908569336
900 24.622217178344727
1000 24.622222900390625
1100 24.622222900390625
1200 24.622224807739258
1300 24.622224807739258
1400 24.622224807739258
1500 24.622220993041992
1600 24.622220993041992
1700 24.622224807739258
1800 24.62222671508789
1900 24.622224807739258
2000 24.622224807739258
2100 24.622220993041992
2200 24.622224807739258
2300 24.622220993041992
2400 24.622220993041992
2500 24.622222900390625
2600 24.622222900390625
2700 24.622220993041992
2800 24.622220993041992
2900 24.622220993041992
3000 24.622220993041992
3100 24.622220993041992
3200 24.622220993041992
3300 24.622224807739258
3400 24.622220993041992
3500 24.622222900390625
3600 24.622220993041992
3700 24.622222900390625
3800 24.622222900390625
3900 24.622220993041992
4000 24.622222900390625
4100 24.622220993041992
4200 24.62222

0.weight
0.bias
2.weight
2.bias
tensor([[-0.1166],
        [-0.6133],
        [ 1.2699],
        [-0.9654]])
tensor([ 2.7585, -0.0126,  0.2314,  3.7987])
tensor([[-1.0509,  0.3716,  0.4810,  2.8314]])
tensor([0.0321])


In [5]:
##reference:https://blog.csdn.net/deephub/article/details/107503883

##dataset2

import torch
import plotly.graph_objects as go
import numpy as np

# Batch Size, Input Neurons, Hidden Neurons, Output Neurons
#just 4 neurons' model can not fit the data very well, the minimal loss is about 11 or 24.
N, D_in, H, D_out = 5, 1, 4, 1

# Create random Tensors to hold inputs and outputs

x = torch.FloatTensor([[0],[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
y = torch.FloatTensor([[0],[1],[2],[3],[2],[1],[1.5],[2],[2.5],[3],[3.5]])



# Use the nn package to define our model
# Linear (Input -> Hidden), ReLU (Non-linearity), Linear (Hidden-> Output)
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

# Define the loss function: Mean Squared Error
# The sum of the squares of the differences between prediction and ground truth
loss_fn = torch.nn.MSELoss(reduction='sum')

# The optimizer does a lot of the work of actually calculating gradients and
# applying backpropagation through the network to update weights
learning_rate = 0.01
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


# Perform 6000 training steps
for t in range(10000):
    # Forward pass: compute predicted y by passing x to the model.
    y_pred = model(x)

    # Compute loss and print it periodically
    loss = loss_fn(y_pred, y)
    if t % 100 == 0:
        print(t, loss.item())

    # Update the network weights using gradient of the loss
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
###################################################
# Draw the original random points as a scatter plot
fig = go.Figure()
fig.add_trace(go.Scatter(x=x.flatten().numpy(), y=y.flatten().numpy(), mode="markers"))

# Generate predictions for evenly spaced x-values between minx and maxx
minx = min(list(x.numpy()))
maxx = max(list(x.numpy()))
c = torch.from_numpy(np.linspace(minx, maxx, num=640)).reshape(-1, 1).float()
d = model(c)

# Draw the predicted functions as a line graph
fig.add_trace(go.Scatter(x=c.flatten().numpy(), y=d.flatten().detach().numpy(), mode="lines"))
fig.show()

# Show corresponding name of every layer
for name in model.state_dict():
  print(name)

# Print weights and bias of certain layers
print(model.state_dict()['0.weight'])
print(model.state_dict()['0.bias'])
print(model.state_dict()['2.weight'])
print(model.state_dict()['2.bias'])


0 16.056364059448242
100 5.150312900543213
200 4.772103786468506
300 4.063037872314453
400 2.868988037109375
500 1.5746634006500244
600 0.5818266868591309
700 0.14091983437538147
800 0.023169005289673805
900 0.0026279257144778967
1000 0.00040776681271381676
1100 2.5949653718271293e-05
1200 0.00012879085261374712
1300 1.4779664070374565e-06
1400 0.000532950391061604
1500 4.396212460733295e-08
1600 6.905973714310676e-05
1700 0.002547820331528783
1800 1.6568293403906864e-06
1900 0.00012079939187970012
2000 8.996198630484287e-06
2100 0.00010237129754386842
2200 1.1453192882981966e-07
2300 2.7652171411318704e-05
2400 9.19405529486994e-09
2500 0.02627066895365715
2600 2.7239099154030555e-07
2700 0.003431048011407256
2800 5.244285716798913e-07
2900 2.202088126068702e-06
3000 4.150990571361035e-05
3100 0.0003956385189667344
3200 0.001498910249210894
3300 2.191141902585514e-06
3400 0.00353780435398221
3500 4.077280379988224e-08
3600 0.0006457557319663465
3700 3.7573834106297e-06
3800 2.93537965

0.weight
0.bias
2.weight
2.bias
tensor([[-0.1561],
        [ 1.0940],
        [ 1.1126],
        [ 0.7476]])
tensor([-9.5220e-01, -3.2832e+00, -1.2049e-03, -3.7408e+00])
tensor([[ 0.0395, -1.8275,  0.8983,  2.0073]])
tensor([-0.0005])


In [ ]:
!apt-get update
!apt-get install texlive texlive-xetex texlive-latex-extra pandoc
!pip install pypandoc

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
!jupyter nbconvert --output-dir='/content' --to latex  '/content/drive/My Drive/Colab Notebooks/HW1Q3(a).ipynb'

In [ ]:
!buf_size=1000000 xelatex --interaction=nonstopmode 'HW1Q3(a).tex'